-- MySQL Script generated by MySQL Workbench
-- Sun Jan 29 12:49:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`courses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`groups` ;

CREATE TABLE IF NOT EXISTS `mydb`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `number_of_students` INT NOT NULL,
  `courses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_groups_courses1_idx` (`courses_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `marks` INT NOT NULL,
  `lesson_type` VARCHAR(45) NOT NULL,
  `truancy` VARCHAR(45) NOT NULL,
  `groups_id` INT NOT NULL,
  `courses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_students_groups1_idx` (`groups_id` ASC) VISIBLE,
  INDEX `fk_students_courses1_idx` (`courses_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`disciplines` ;

CREATE TABLE IF NOT EXISTS `mydb`.`disciplines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `number_of_hours` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`truancy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`truancy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`truancy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `reason` VARCHAR(45) NOT NULL,
  `students_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_truancy_students1_idx` (`students_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`courses_has_disciplines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`courses_has_disciplines` ;

CREATE TABLE IF NOT EXISTS `mydb`.`courses_has_disciplines` (
  `courses_id` INT NOT NULL,
  `disciplines_id` INT NOT NULL,
  PRIMARY KEY (`courses_id`, `disciplines_id`),
  INDEX `fk_courses_has_disciplines_disciplines1_idx` (`disciplines_id` ASC) VISIBLE,
  INDEX `fk_courses_has_disciplines_courses1_idx` (`courses_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students_has_disciplines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`students_has_disciplines` ;

CREATE TABLE IF NOT EXISTS `mydb`.`students_has_disciplines` (
  `students_id` INT NOT NULL,
  `disciplines_id` INT NOT NULL,
  PRIMARY KEY (`students_id`, `disciplines_id`),
  INDEX `fk_students_has_disciplines_disciplines1_idx` (`disciplines_id` ASC) VISIBLE,
  INDEX `fk_students_has_disciplines_students1_idx` (`students_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
